create table if not exists feature (
    feature_id bigint not null,
    discriminator varchar(255) ,
    fk_format_id bigint not null,
    identifier varchar(255)  not null,
    sta_identifier varchar(255)  not null,
    fk_identifier_codespace_id bigint,
    name varchar(255) ,
    fk_name_codespace_id bigint,
    description string ,
    xml string ,
    url varchar(255) ,
    geom geometry,
    constraint feature_pkey primary key (feature_id),
    constraint un_feature_identifier unique (identifier),
    constraint un_feature_staidentifier unique (sta_identifier),
    constraint un_feature_url unique (url)
    );



create table if not exists dataset (
                                       dataset_id bigint not null,
                                       discriminator varchar(255),
    identifier varchar(255),
    sta_identifier varchar(255),
    name varchar(255),
    description string,
    first_time timestamp,
    last_time timestamp,
    result_time_start timestamp,
    result_time_end timestamp,
    observed_area geometry,
    fk_procedure_id bigint not null,
    fk_phenomenon_id bigint not null,
    fk_offering_id bigint not null,
    fk_category_id bigint not null,
    fk_feature_id bigint,
    fk_platform_id bigint,
    fk_unit_id bigint,
    fk_format_id bigint,
    fk_aggregation_id bigint,
    first_value numeric(20, 10),
    last_value numeric(20, 10),
    fk_first_observation_id bigint,
    fk_last_observation_id bigint,
    dataset_type varchar(255) not null default cast('not_initialized' as varchar),
    observation_type varchar(255) not null default cast('not_initialized' as varchar),
    value_type varchar(255) not null default cast('not_initialized' as varchar),
    is_deleted smallint not null default 0,
    is_disabled smallint not null default 0,
    is_published smallint not null default 1,
    is_mobile smallint default 0,
    is_insitu smallint default 1,
    is_hidden smallint not null default 0,
    origin_timezone varchar(40),
    decimals int,
    fk_identifier_codespace_id bigint,
    fk_name_codespace_id bigint,
    fk_value_profile_id bigint,
    constraint dataset_pkey primary key (dataset_id),
    constraint un_dataset_identifier unique (identifier),
    constraint un_dataset_identity unique (
                                              fk_procedure_id,
                                              fk_phenomenon_id,
                                              fk_offering_id,
                                              fk_category_id,
                                              fk_feature_id,
                                              fk_platform_id,
                                              fk_unit_id
                                          ),
    constraint un_dataset_staidentifier unique (sta_identifier),
    constraint fk_dataset_feature foreign key (fk_feature_id)
                REFERENCES feature (feature_id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
    );

create table if not exists observation (
    observation_id bigint not null,
    value_type varchar(255) not null,
    fk_dataset_id bigint not null,
    sampling_time_start timestamp not null,
    sampling_time_end timestamp not null,
    result_time timestamp,
    identifier varchar(255),
    sta_identifier varchar(255) not null,
    fk_identifier_codespace_id bigint,
    name varchar(255),
    fk_name_codespace_id bigint,
    description string,
    is_deleted smallint not null default 0,
    valid_time_start timestamp,
    valid_time_end timestamp,
    sampling_geometry geometry,
    value_identifier varchar(255),
    value_name varchar(255),
    value_description varchar(255),
    vertical_from numeric(20, 10) not null default 0,
    vertical_to numeric(20, 10) not null default 0,
    fk_parent_observation_id bigint,
    value_quantity numeric(20, 10),
    value_text varchar(255),
    value_count int,
    value_category varchar(255),
    value_boolean smallint,
    detection_limit_flag smallint,
    detection_limit numeric(20, 10),
    value_reference varchar(255),
    value_geometry geometry,
    value_array string,
    fk_result_template_id bigint,
    constraint observation_pkey primary key (observation_id),
    constraint un_observation_identifier unique (identifier),
    constraint un_observation_identity unique (
                                                  value_type,
                                                  fk_dataset_id,
                                                  sampling_time_start,
                                                  sampling_time_end,
                                                  result_time,
                                                  vertical_from,
                                                  vertical_to
                                              ),
    constraint un_observation_staidentifier unique (sta_identifier),
    constraint fk_dataset foreign key (fk_dataset_id)
                REFERENCES dataset (dataset_id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
    );