<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.n52.sensorweb-server.sta</groupId>
        <artifactId>sta-parent</artifactId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>sta-dao-cloudnative</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.n52.sensorweb-server.db-model</groupId>
            <artifactId>db-model-entities</artifactId>
        </dependency>
        <dependency>
            <groupId>org.n52.sensorweb-server.db-model</groupId>
            <artifactId>db-model-mappings</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.n52.sensorweb-server.db-model</groupId>
            <artifactId>db-model-types</artifactId>
        </dependency>

        <dependency>
            <groupId>org.n52.arctic-sea</groupId>
            <artifactId>shetland</artifactId>
        </dependency>
        <dependency>
            <groupId>org.n52.arctic-sea</groupId>
            <artifactId>svalbard-odata</artifactId>
        </dependency>
        <dependency>
            <groupId>org.n52.arctic-sea</groupId>
            <artifactId>janmayen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.duckdb</groupId>
            <artifactId>duckdb_jdbc</artifactId>
            <version>0.10.0</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-jooq</artifactId>-->
<!--            <version>2.3.5.RELEASE</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jooq</groupId>-->
<!--                    <artifactId>jooq</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.19.10</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.jooq</groupId>-->
<!--            <artifactId>jooq-codegen</artifactId>-->
<!--            <version>3.19.10</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jooq</groupId>-->
<!--                    <artifactId>jooq</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jooq</groupId>-->
<!--                    <artifactId>jooq-meta</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jooq</groupId>-->
<!--            <artifactId>jooq-meta</artifactId>-->
<!--            <version>3.19.10</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jooq</groupId>-->
<!--                    <artifactId>jooq</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.n52.sensorweb-server.sta</groupId>
            <artifactId>sta-dao</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.n52.sensorweb-server.sta</groupId>
            <artifactId>sta-dao-postgres</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <usedDependencies>
                        <dependency>org.n52.sensorweb-server.db-model:db-model-mappings</dependency>
                        <dependency>org.n52.sensorweb-server.db-model:db-model-entities</dependency>
                    </usedDependencies>
                </configuration>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.jooq</groupId>-->
<!--                <artifactId>jooq-codegen-maven</artifactId>-->
<!--                <version>3.19.10</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>generate-h2-jpa</id>-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <generator>-->
<!--                                <database>-->
<!--                                    <name>org.jooq.meta.extensions.jpa.JPADatabase</name>-->
<!--                                    <properties>-->
<!--                                        <property>-->
<!--                                            <key>packages</key>-->
<!--                                            <value>-->
<!--                                                org.n52.series.db.beans.sta,-->
<!--                                                org.n52.series.db.beans.parameter.dataset,-->
<!--                                                org.n52.series.db.beans.parameter.procedure,-->
<!--                                                org.n52.series.db.beans.parameter.platform,-->
<!--                                                org.n52.series.db.beans.parameter.observation,-->
<!--                                                org.n52.series.db.beans.parameter.feature,-->
<!--                                                org.n52.series.db.beans.parameter.location,-->
<!--                                                org.n52.series.db.beans.parameter.phenomenon,-->
<!--                                                org.n52.series.db.beans-->
<!--                                            </value>-->
<!--                                        </property>-->
<!--                                        <property>-->
<!--                                            <key>persistenceXml</key>-->
<!--                                            <value>src/main/resources/META-INF/sta-vanilla.xml</value>-->
<!--                                        </property>-->
<!--                                    </properties>-->
<!--                                    <includes>.*</includes>-->
<!--                                </database>-->
<!--                                <generate>-->
<!--                                </generate>-->
<!--                                <target>-->
<!--                                    <packageName>package org.n52.sta.cndao.jooq</packageName>-->
<!--                                    <directory>src/main/java</directory>-->
<!--                                </target>-->
<!--                            </generator>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--                <dependencies>-->
<!--                    <dependency>-->
<!--                        <groupId>org.jooq</groupId>-->
<!--                        <artifactId>jooq-meta-extensions-hibernate</artifactId>-->
<!--                        <version>3.19.10</version>-->
<!--                    </dependency>-->
<!--                    <dependency>-->
<!--                        <groupId>jakarta.persistence</groupId>-->
<!--                        <artifactId>jakarta.persistence-api</artifactId>-->
<!--                        <version>3.1.0</version>-->
<!--                    </dependency>-->
<!--                </dependencies>-->
<!--            </plugin>-->
        </plugins>
    </build>
</project>