

server:
  feature:
    observation:
      # Key that holds information about the samplingGeometry
      samplingGeometry: geometry

## Service Configuration
service:
  connector:
    # hereon config
    hereon:
      username:
      password:
      url:
        token:
