# Settings
server:
  feature:
    httpReadOnly: true
    mqttReadOnly: true
    observation:
      # Key that holds information about Observation->samplingGeometry
      samplingGeometry: geometry


spring:
  profiles:
    active: hereon

# MQTT is disabled
mqtt:
  broker:
    plaintcp:
      enabled: false
    websocket:
      enabled: false

service:
  connector:
    # hereon config
    hereon:
      username:
      password:
      url:
        token:
