@startuml Detailed Context

title STA package/module graph (commit 547fdd)


file "War File" as war
file "Executable Jar" as jar

database database #dd7766

frame "SensorThings API" as sta {
    together {
        [mqtt]
        [http]
    }
    
    together {
        [api]
        [data-provider-hibernate] as dph
    }

    together {
        [app]
        [webapp]
    }

    webapp .up.> war : //creates//
    app .up.> jar : //creates//
    http --> api
    mqtt --> api


    api --> dph
    dph --> database
}

frame "arctic-sea" as arcticsea {
    [shetland] as shetland
    note bottom of shetland : Meta Definitions

    [svalbard-odata] as svalbard
    note bottom of svalbard : OData Query Parsing
}

actor "data provider" as data_provider #dd7766
actor "sensor" as sensor #dd7766
actor "client" as client #dd7766

() Rest as sta_api
sta ..> arcticsea
http -up- sta_api

client ..> sta_api
sensor ..> sta_api

data_provider .d.> mqtt

@enduml
