/*
 * Copyright (C) 2018-2021 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */

package org.n52.sta.data.cloudnative.service;

import org.jooq.Condition;
import org.jooq.Field;
import org.locationtech.jts.geom.*;
import org.locationtech.jts.io.WKBWriter;
import org.n52.janmayen.http.HTTPStatus;
import org.n52.shetland.filter.ExpandFilter;
import org.n52.shetland.filter.ExpandItem;
import org.n52.shetland.oasis.odata.query.option.QueryOptions;
import org.n52.shetland.ogc.sta.StaConstants;
import org.n52.shetland.ogc.sta.exception.STACRUDException;
import org.n52.shetland.ogc.sta.exception.STAInvalidQueryException;
import org.n52.shetland.ogc.sta.model.STAEntityDefinition;
import org.n52.sta.api.dto.DatastreamDTO;
import org.n52.sta.api.dto.FeatureOfInterestDTO;
import org.n52.sta.api.dto.LocationDTO;
import org.n52.sta.api.dto.ObservationDTO;
import org.n52.sta.api.dto.impl.FeatureOfInterest;
import org.n52.sta.data.cloudnative.condition.DatastreamQueryConditions;
import org.n52.sta.data.cloudnative.condition.FeatureOfInterestQueryConditions;
import org.n52.sta.data.cloudnative.condition.ObservationQueryConditions;
import org.n52.sta.data.cloudnative.condition.StaEntity;
import org.n52.sta.data.cloudnative.dao.FeatureOfInterestDao;
import org.n52.sta.data.cloudnative.dao.impl.DatastreamDaoImpl;
import org.n52.sta.data.cloudnative.dao.impl.FeatureOfInterestDaoImpl;
import org.n52.sta.data.cloudnative.dao.impl.FormatDaoImpl;
import org.n52.sta.data.cloudnative.dao.impl.ObservationDaoImpl;
import org.n52.sta.data.cloudnative.schema.tables.pojos.Dataset;
import org.n52.sta.data.cloudnative.schema.tables.pojos.Feature;
import org.n52.sta.data.cloudnative.schema.tables.pojos.Format;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.DependsOn;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpMethod;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

import static org.n52.sta.data.cloudnative.dao.StaEntityDao.INVALID_EXPAND_OPTION_SUPPLIED;

/**
 * @author <a href="mailto:humaid.kidwai@ucalgary.ca">Humaid Kidwai</a>
 */
@Component
@DependsOn({"springApplicationContext"})
@Transactional
public class FeatureOfInterestService extends AbstractSensorThingsEntityServiceImpl<
        FeatureOfInterestDao,
        FeatureOfInterestDTO> {

    private static final Logger LOGGER = LoggerFactory.getLogger(FeatureOfInterestService.class);
    static final String AUTOGENERATED_KEY = "autogenerated";
    private final ObservationQueryConditions oQC;
    private final FeatureOfInterestQueryConditions foiQC;
    private final DatastreamQueryConditions dsQC;

    private final ObservationDaoImpl observationDao;
    private final DatastreamDaoImpl datastreamDao;
    private final FeatureOfInterestDaoImpl featureDao;
    private final FormatService formatService;
    private final FormatDaoImpl formatDao;
    private final AtomicLong TS = new AtomicLong();

    public FeatureOfInterestService(Class<FeatureOfInterestDTO> entityClass,
                                    FormatService formatService,
                                    FormatDaoImpl formatDao,
                                    ObservationDaoImpl observationDao,
                                    DatastreamDaoImpl datastreamDao,
                                    FeatureOfInterestDaoImpl featureDao,
                                    ObservationQueryConditions oQC,
                                    FeatureOfInterestQueryConditions foiQC,
                                    DatastreamQueryConditions dsQC) {
        super(featureDao, entityClass);
        this.formatService = formatService;
        this.formatDao = formatDao;
        this.observationDao = observationDao;
        this.datastreamDao = datastreamDao;
        this.featureDao = featureDao;
        this.oQC = oQC;
        this.foiQC = foiQC;
        this.dsQC = dsQC;
    }

    @Override
    protected FeatureOfInterestDTO fetchExpandEntitiesWithFilter(FeatureOfInterestDTO entity,
                                                                 ExpandFilter expandOption)
            throws STACRUDException, STAInvalidQueryException {

        Set<ObservationDTO> observations = new HashSet<>();
        for (ExpandItem expandItem : expandOption.getItems()) {
            String expandProperty = expandItem.getPath();
            if (STAEntityDefinition.OBSERVATIONS.equals(expandProperty)) {
                Page<ObservationDTO> observation = getObservationService()
                        .getEntityCollectionByRelatedEntityRaw(entity.getId(),
                                STAEntityDefinition.FEATURES_OF_INTEREST,
                                expandItem.getQueryOptions());
                observations.addAll(observation.toSet());
            } else {
                throw new STAInvalidQueryException(String.format(INVALID_EXPAND_OPTION_SUPPLIED,
                        expandProperty,
                        StaConstants.FEATURE_OF_INTEREST));
            }
        }
        entity.setObservations(observations);
        return entity;
    }

    @Override
    protected Condition byRelatedEntityFilter(String relatedId, String relatedType, String ownId) {
        Condition filter;
        switch (relatedType) {
            case STAEntityDefinition.OBSERVATIONS: {
                filter = foiQC.withObservationStaIdentifier(relatedId);
                break;
            }
            default:
                throw new IllegalStateException(String.format(TRYING_TO_FILTER_BY_UNRELATED_TYPE, relatedType));
        }

        if (ownId != null) {
            filter = filter.and(foiQC.withStaIdentifier(ownId));
        }
        return filter;
    }

    @Override
    protected FeatureOfInterestDTO createOrfetch(FeatureOfInterestDTO feature)
            throws STACRUDException, STAInvalidQueryException {

        // Get by reference
        if (feature.getId() != null && feature.getName() == null) {
            Optional<FeatureOfInterestDTO> optionalEntity =
                    featureDao.findByStaIdentifier(feature.getId(), null, entityClass);
            if (optionalEntity.isPresent()) {
                return optionalEntity.get();
            } else {
                throw new STACRUDException(String.format(NO_S_WITH_ID_S_FOUND,
                        StaConstants.FEATURE_OF_INTEREST,
                        feature.getId()));
            }
        }
        if (feature.getId() == null) {
            if (featureDao.existsByName(feature.getName(), entityClass)) {
                Iterable<FeatureOfInterestDTO> features =
                        featureDao.findAll(foiQC.withName(feature.getName()),null, entityClass);
                FeatureOfInterestDTO existingFeature = alreadyExistsFeature(features, feature);
                if (existingFeature != null) {
                    return existingFeature;
                }
            }
        }
        synchronized (getLock(feature.getId())) {
            // Check whether feature exists by sta identifier
            if (featureDao.existsByStaIdentifier(feature.getId(), entityClass)) {
                throw new STACRUDException("StaIdentifier already exists!", HTTPStatus.CONFLICT);
            } else {
                // Autogenerate Identifier
                feature.setId(getUniqueTimestamp().toString());
                featureDao.save(POJOWrapper(feature));
                if (feature.getProperties() != null) {
                    featureDao.saveFeatureParameters(feature.getId(), feature.getProperties());
                }
                return feature;
            }
        }
    }

    private FeatureOfInterestDTO alreadyExistsFeature(Iterable<FeatureOfInterestDTO> features,
                                                      FeatureOfInterestDTO feature) {
        for (FeatureOfInterestDTO foi : features) {
            if (foi.getFeature() != null &&
                    feature.getFeature() != null &&
                    foi.getFeature().equals(feature.getFeature()) &&
                    foi.getDescription().equals(feature.getDescription())) {
                return foi;
            }
        }
        return null;

    }

    private Feature POJOWrapper(FeatureOfInterestDTO feature) throws STACRUDException {
        Feature featurePOJO = new Feature();
        featurePOJO.setFeatureId(Long.valueOf(feature.getId()));
        featurePOJO.setIdentifier(feature.getId());
        featurePOJO.setName(feature.getName());
        featurePOJO.setDescription(feature.getDescription());
        featurePOJO.setXml(null);
        featurePOJO.setGeom(new WKBWriter().write(feature.getFeature()));
        Format formatPOJO = formatService.createOrFetchFormat(feature.getEncodingType());
        featurePOJO.setFkFormatId(formatPOJO.getFormatId());
        return featurePOJO;
    }

    @Override
    protected FeatureOfInterestDTO createOrUpdate(FeatureOfInterestDTO entity)
            throws STACRUDException, STAInvalidQueryException {
        if (entity.getId() != null && featureDao.existsByStaIdentifier(entity.getId(), entityClass)) {
            return updateEntity(entity.getId(), entity, HttpMethod.PATCH);
        }
        return createOrfetch(entity);
    }

    @Override
    protected FeatureOfInterestDTO updateEntity(String id, FeatureOfInterestDTO entity, HttpMethod method)
            throws STACRUDException, STAInvalidQueryException {
        if (HttpMethod.PATCH.equals(method)) {
            synchronized (getLock(id)) {
                Optional<FeatureOfInterestDTO> existing = featureDao.findByStaIdentifier(id,
                        null,
                        entityClass);
                if (existing.isPresent()) {
                    FeatureOfInterestDTO merged = merge(existing.get(), entity);
                    featureDao.update(POJOWrapper(merged));
                    return merged;
                }
                throw new STACRUDException(UNABLE_TO_UPDATE_ENTITY_NOT_FOUND, HTTPStatus.NOT_FOUND);
            }
        } else if (HttpMethod.PUT.equals(method)) {
            throw new STACRUDException(HTTP_PUT_IS_NOT_YET_SUPPORTED, HTTPStatus.NOT_IMPLEMENTED);
        }
        throw new STACRUDException(INVALID_HTTP_METHOD_FOR_UPDATING_ENTITY, HTTPStatus.BAD_REQUEST);
    }

    @Override
    protected void deleteEntity(String id)
            throws STACRUDException, STAInvalidQueryException {
        synchronized (getLock(id)) {
            if (featureDao.existsByStaIdentifier(id, entityClass)) {
                // check observations
                deleteRelatedObservationsAndUpdateDatasets(id);
                FeatureOfInterestDTO foi = featureDao.findByStaIdentifier(id, null, entityClass).get();

                if (foi.getProperties() != null) {
                    featureDao.deleteFeatureParameters(foi.getId(), foi.getProperties());
                }
                featureDao.deleteByStaIdentifier(id, entityClass);
            } else {
                throw new STACRUDException(UNABLE_TO_DELETE_ENTITY_NOT_FOUND, HTTPStatus.NOT_FOUND);
            }
        }

    }

    private void deleteRelatedObservationsAndUpdateDatasets(String featureId)
            throws STACRUDException, STAInvalidQueryException {

        synchronized (getLock(featureId)) {
            Dataset dataset = datastreamDao.findOnePOJO(dsQC.withFeatureStaIdentifier(featureId));
            // delete related observations
            observationDao.deleteAllByDatasetIdIn(Collections.singleton(dataset.getDatasetId()));
            // only delete if we are part of an aggregation
            // if we are not part of an aggregation we must not delete as this would also delete the whole datastream
            if (dataset.getFkAggregationId() != null && dataset.getFkAggregationId() != 1L) {
                datastreamDao.deleteById(dataset.getDatasetId());
            }
        }
    }

    @Override
    protected FeatureOfInterestDTO merge(FeatureOfInterestDTO existing, FeatureOfInterestDTO toMerge)
            throws STACRUDException {
        mergeNameDescription(existing, toMerge);
        if (toMerge.getFeature() != null) {
            existing.setFeature(toMerge.getFeature());
        }
        mergeFeatureType(existing);
        return existing;
    }

    private void mergeFeatureType(FeatureOfInterestDTO existing) {
        String encodingType = formatService.getFormatDefinitionFromGeometry(existing.getFeature());
        if(!encodingType.equals(existing.getEncodingType())) {
            existing.setEncodingType(encodingType);
        }
    }

    public FeatureOfInterestDTO getEntityByDatasetIdRaw(Long id, QueryOptions queryOptions)
            throws STACRUDException {
        try {
            Condition predicate = StaEntity.DATASTREAM.DATASET_ID.eq(id);
            Dataset dataset = datastreamDao
                    .selectQueryBuilder(predicate, DatastreamDTO.class, null, queryOptions)
                    .fetchOneInto(Dataset.class);
            Long featureId = dataset.getFkFeatureId();

            FeatureOfInterestDTO entity = featureDao
                    .findById(featureId, queryOptions, entityClass)
                    .get();

            if (queryOptions.hasExpandFilter()) {
                return fetchExpandEntitiesWithFilter(entity, queryOptions.getExpandFilter());
            } else {
                return entity;
            }
        } catch (RuntimeException | STAInvalidQueryException e) {
            throw new STACRUDException(e.getMessage(), e);
        }
    }

    public FeatureOfInterestDTO createFeatureOfInterest(LocationDTO location) throws STACRUDException {
        Feature featureOfInterestPOJO = new Feature();

        // TODO: Why use the same Id as Location?
        featureOfInterestPOJO.setStaIdentifier(location.getId());
        featureOfInterestPOJO.setIdentifier(location.getEncodingType());
        featureOfInterestPOJO.setFeatureId(Long.valueOf(location.getId()));
        featureOfInterestPOJO.setName(location.getName());
        featureOfInterestPOJO.setDescription(location.getDescription());
        featureOfInterestPOJO.setGeom(new WKBWriter().write(location.getGeometry()));
        // Used to distinguish in FeatureOfInterestService
        featureOfInterestPOJO.setXml(AUTOGENERATED_KEY);
        Format format = formatService.createFormatFromGeometry(location.getGeometry());
        featureOfInterestPOJO.setFkFormatId(format.getFormatId());

        featureDao.save(featureOfInterestPOJO);
        return DTOWrapper(featureOfInterestPOJO, location.getGeometry(), format);
    }

    private FeatureOfInterestDTO DTOWrapper(Feature featurePOJO, Geometry geometry, Format format) {
        FeatureOfInterestDTO feature = new FeatureOfInterest();
        feature.setId(featurePOJO.getStaIdentifier());
        feature.setFeature(geometry);
        feature.setName(featurePOJO.getName());
        feature.setDescription(featurePOJO.getDescription());
        feature.setEncodingType(format.getDefinition());
        return feature;
    }

    /**
     * Extends the geometry of the FOI with given id by geom. Used for automatically expanding FOIs e.g. for
     * Observations along a track.
     * Used for non-standard feature 'updateFOI'.
     *
     * @param id   id of the FOI
     * @param geom geom to expand the existing Geometry
     * @throws STACRUDException if an error occurred
     */
    public void updateFeatureOfInterestGeometry(String id, Geometry geom)
            throws STACRUDException, STAInvalidQueryException {
        synchronized (getLock(id)) {
            Optional<FeatureOfInterestDTO> existing =
                    featureDao.findByStaIdentifier(id, null, entityClass);
            if (existing.isPresent()) {
                FeatureOfInterestDTO featureOfInterest = existing.get();
                if (featureOfInterest.getFeature() != null) {
                    if (geom instanceof Point) {
                        List<Coordinate> coords = new ArrayList<>();
                        Geometry convert = featureOfInterest.getFeature();
                        if (convert instanceof Point) {
                            coords.add(convert.getCoordinate());
                        } else if (convert instanceof LineString || convert instanceof GeometryCollection) {
                            coords.addAll(Arrays.asList(convert.getCoordinates()));
                        } else {
                            LOGGER.error("Could not update FOI geometry. Unknown GeometryType." +
                                    convert.getClass().getSimpleName());
                            throw new STACRUDException(
                                    "Could not update FeatureOfInterest. Unknown GeometryType:" +
                                            convert.getClass().getSimpleName());
                        }
                        Geometry newGeometry;
                        if (!coords.isEmpty()) {
                            coords.add(geom.getCoordinate());
                            newGeometry = new GeometryFactory()
                                    .createLineString(coords.toArray(new Coordinate[coords.size()]));
                        } else {
                            newGeometry =
                                    new GeometryFactory().createPoint(geom.getCoordinate());
                        }
                        newGeometry.setSRID(featureOfInterest.getFeature().getSRID());
                        featureOfInterest.setFeature(newGeometry);
                    }
                } else {
                    featureOfInterest.setFeature(geom);
                }
                featureDao.update(POJOWrapper(featureOfInterest));
            } else {
                throw new STACRUDException("Could not update FeatureOfInterest. No FeatureOfInterest with id \"" + id +
                        "\" found!");
            }
        }
    }

    @Override
    protected String checkPropertyName(String property) {
        return foiQC.checkPropertyName(property).getName();
    }

    @Override
    Field<String> getStaEntityId() {
        return StaEntity.FEATURE_OF_INTEREST.STA_IDENTIFIER;
    }

    @Override
    AtomicLong getStaEntityTS() {
        return TS;
    }
}
