@startuml 52n SensorThings API, DAO (Datastream)

abstract class "AbstractSensorThingsEntityServiceImpl" as entity_service {
    {abstract} createFetchGraph
    {abstract} fetchExpandEntitiesWithFilter
    {abstract} byRelatedEntityFilter
    {abstract} createOrFetch
    {abstract} updateEntity
    {abstract} createOrUpdate
}

package services {

    class "EntityServiceRegistry" as entity_service_registry
    class "DatastreamService<AbstractDatasetEntity>" as ds_service
    class "OfferingService" as offering_service
    class "FormatService" as format_service

    frame util {
        interface "HibernateSpatialCriteriaBuilder" as hb_spatial_criteria_builder
        class "HibernateSpatialCriteriaBuilderImpl" as hb_spatial_criteria_builder_impl

        hb_spatial_criteria_builder_impl ..> hb_spatial_criteria_builder
    }

}

package query {
    class "DatastreamQuerySpecifications" as ds_query_specs
}


package repositories {

    class "UnitRepository" as unit_repo
    class "ObservationRepository" as observation_repo
    class "DataStreamParameterRepository" as ds_parameter_repo
    class "EntityGraphRepository" as entitygraph_repo
}

interface "EntityManager" as em

entity_service -up-> em
ds_service -u-|> entity_service
ds_service --> format_service
ds_service --> offering_service


@enduml