
@startwbs AST Query, Example 1

' $expand=Datastream
'&$orderby=Datastreams/id desc, phenomenonTime

+_ /Observations(42)?
++_ $expand
+++_ Datastream
++_ $orderBy
+++_ ,
++++_ Datastreams/id
++++_ desc
+++_ phenomenonTime

@endwbs


@startwbs AST Query, Example 2

' $filter=time gt 2000-11-27T10:44:51.331Z and time lt 2020-08-27T15:45:31.021Z
'&$expand=Things($select=name)
'&$select=time
'&$top=1000

+_ /HistoricalLocation(42)?
++_ $filter
+++_ and
++++_ gt
+++++_ time
+++++_ 2000-11-27T10:44:51.331Z
++++_ lt
+++++_ time
+++++_ 2020-08-27T15:45:31.021Z
++_ $expand
+++_ $Things()
++++_ =
+++++_ $select
+++++_ name
++_ $select
+++_ time
++_ $top
+++_ 1000

@endwbs


@startwbs AST Query, Example 3

' all features having locations within distance one around POINT(-122 43)
'
' $filter=geo.distance(Locations/location, geography'POINT(-122 43)') gt 1

+_ /Things(42)?
++_ $filter
+++_ lt
++++_ geo.distance()
+++++_ Locations/location
+++++_ geography'POINT(-122 43)
++++_ 1

@endwbs