# Adapted from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

env:
  TITLE: "52°North SensorThingsAPI"
  VENDOR: "52°North GmbH"
  AUTHORS: "https://github.com/52North/sensorweb-server-sta/graphs/contributors"
  DESCRIPTION: "Implementation of the OGC SensorThings API Part I: Sensing Version 1.1 (18-088)"

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildkit env
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for tagging Docker Image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: 52north/sensorweb-server-sta
          labels: |
            -  org.opencontainers.image.authors=$AUTHORS 
            -  org.opencontainers.image.vendor=$VENDOR
            -  org.opencontainers.image.description=$DESCRIPTION
            -  org.opencontainers.image.title=$TITLE
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
