name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Cache Maven Repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -fae -U -B clean license:check install -P check --file pom.xml
