name: Java CI on Pull Request

on:
  pull_request:
   branches:
      - 'sta-slicing'
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        java: [ 11 ]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} compile
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    
    - name: Cache Maven Repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -fae -U -B clean license:check install --file pom.xml
